### ISSUE TITLE
build: increase jax upper bound

### ISSUE THREAD

**Issue by cemlyn007** [instadeepai/jumanji#171] opened 2023-06-15 12:36 UTC
https://github.com/instadeepai/jumanji/blob/ed13d82e2a1c4f734fabe41b173411467e737606/requirements/requirements.txt#LL4C17-L4C17

Is it possible to change this to be jax < 0.5?

**Comment by clement-bonnet** [comment] 2023-06-15 12:37
Hi, this seems to be a duplicate of #168

**Comment by clement-bonnet** [comment] 2023-06-18 17:52
Resolve in #174

**Closed by clement-bonnet** 2023-06-18 17:52 UTC
